// Package models contains data models generated by go-swagger.
//
// To regenerate models from the OpenAPI spec, run:
//
//	go generate ./...
//
//go:generate swagger generate model -f ../../../../api/swagger.yaml -m models --target ..
package models
