// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSnippetRequest get snippet request
//
// swagger:model GetSnippetRequest
type GetSnippetRequest struct {

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this get snippet request
func (m *GetSnippetRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get snippet request based on context it is used
func (m *GetSnippetRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetSnippetRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSnippetRequest) UnmarshalBinary(b []byte) error {
	var res GetSnippetRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
