server:
  port: 8091
  data_dir: "./data"
  rate_limit: 5
  max_total_submissions: 100
  max_code_chars: 3000

languages:
  golang:
    image: "golang:1.25-alpine"
    version: "1.25"
  python:
    image: "python:3.13-alpine"
    version: "3.13"
  javascript:
    image: "node:24.14.0-alpine"
    version: "24.14.0"
  rust:
    image: "rust:1.93.1-alpine"
    version: "1.93.1"
  cpp:
    image: "gcc:13"
    version: "13"
